-- AI 知识库建设模块的全部表结构。设计依据与每个字段的取舍理由见
-- tech/knowledge-base/data-model.md §3，两者必须保持一致（该文档里的 DDL 与本文件
-- 逐字对应，方便直接 diff 出漂移）。
--
-- 五张表建在同一个 migration 里而不拆成五个文件：它们外键相互引用，是一个内聚的
-- 模块结构，拆开只会引入"必须按序执行"的隐含依赖而不产生任何收益。
--
-- 全局约定：
--   * 主键 bigint identity；时间戳 timestamptz；
--   * 枚举用 varchar + check 约束，不用 PostgreSQL 原生 enum（原生 enum 增删值要
--     ALTER TYPE，演进成本更高）；
--   * 业务表统一逻辑删除（docs/prd/2026-07-25-knowledge-base-prd.md §7.6），
--     唯一性约束因此必须写成 where deleted = false 的部分唯一索引，否则
--     "删掉再建同名"会失败。

create table knowledge_base (
    id                   bigint generated by default as identity primary key,
    name                 varchar(128)  not null,
    description          varchar(1024),
    embedding_model      varchar(128)  not null,
    embedding_dimensions integer       not null,
    deleted              boolean       not null default false,
    delete_time          timestamptz,
    create_time          timestamptz   not null default now(),
    update_time          timestamptz   not null default now()
);

create unique index uk_knowledge_base_name on knowledge_base (name) where deleted = false;

create table source_document (
    id                  bigint generated by default as identity primary key,
    kb_id               bigint        not null references knowledge_base (id),
    name                varchar(256)  not null,
    source_type         varchar(16)   not null,
    -- FILE 与 URL 共用
    file_key            varchar(512),
    file_size           bigint,
    content_type        varchar(128),
    content_hash        varchar(64),
    -- 仅 URL
    source_uri          varchar(2048),
    http_etag           varchar(256),
    http_last_modified  varchar(128),
    sync_enabled        boolean       not null default false,
    sync_cron           varchar(64),
    next_sync_time      timestamptz,
    last_sync_time      timestamptz,
    -- 处理状态
    status              varchar(16)   not null default 'PENDING',
    revision            integer       not null default 0,
    chunk_count         integer       not null default 0,
    error_message       varchar(2048),
    enabled             boolean       not null default true,
    deleted             boolean       not null default false,
    delete_time         timestamptz,
    create_time         timestamptz   not null default now(),
    update_time         timestamptz   not null default now(),

    constraint ck_source_document_source_type check (source_type in ('FILE', 'URL')),
    constraint ck_source_document_status
        check (status in ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')),
    constraint ck_source_document_url_fields
        check (source_type <> 'URL' or source_uri is not null),
    -- "只有 URL 来源能开定时同步" 是 PRD §4.3 的硬性边界，值得在最底层兜一道，
    -- 而不是只靠 Service 层校验。
    constraint ck_source_document_sync_fields
        check (sync_enabled = false or (source_type = 'URL' and sync_cron is not null))
);

create index idx_source_document_kb on source_document (kb_id, deleted, id desc);

-- 部分索引：定时扫描只关心开了同步的 URL 文档。注意 status <> 'RUNNING' 有意
-- 没有放进索引条件——status 是高频更新列，放进部分索引条件会让每次状态变更都
-- 触发索引项的增删。
create index idx_source_document_sync on source_document (next_sync_time)
    where deleted = false and sync_enabled = true and source_type = 'URL';

create table document_chunk (
    id           bigint generated by default as identity primary key,
    kb_id        bigint      not null references knowledge_base (id),
    doc_id       bigint      not null references source_document (id),
    revision     integer     not null,
    chunk_index  integer     not null,
    content      text        not null,
    char_count   integer     not null,
    token_count  integer     not null,
    content_hash varchar(64) not null,
    enabled      boolean     not null default true,
    deleted      boolean     not null default false,
    delete_time  timestamptz,
    create_time  timestamptz not null default now(),
    update_time  timestamptz not null default now()
);

create index idx_document_chunk_doc on document_chunk (doc_id, deleted, chunk_index);
create index idx_document_chunk_kb on document_chunk (kb_id, deleted);

-- 派生索引表，是五张表里唯一不做逻辑删除的（PRD §7.6 例外 1）。三条不变量由
-- Service 层保证，Phase 3 检索侧依赖它们直接查本表而不关联业务表过滤：
--   1. 只做物理删除，无 deleted 列；
--   2. 表中每一行都对应一个未删除、已启用、且所属文档也未删除已启用的分块；
--   3. chunk_id 作主键 —— 一个分块最多一条向量，更新分块内容时 delete + insert
--      同一个 chunk_id，天然不会产生重复行。
-- vector(1024) 的维度与 app.embedding.dimensions 必须一致，应用启动时校验。
create table document_chunk_embedding (
    chunk_id    bigint      primary key references document_chunk (id),
    kb_id       bigint      not null references knowledge_base (id),
    doc_id      bigint      not null references source_document (id),
    embedding   vector(1024) not null,
    create_time timestamptz not null default now()
);

create index idx_chunk_embedding_kb on document_chunk_embedding (kb_id);
create index idx_chunk_embedding_hnsw on document_chunk_embedding
    using hnsw (embedding vector_cosine_ops);

-- 同时扮演三个角色，都是有意合并的：异步任务队列（status='QUEUED' 的行就是待办）、
-- 执行历史（界面上可见每次同步/分块的结果，含 SKIPPED）、失败诊断（phase 说明失败
-- 发生在哪一步）。
create table ingestion_run (
    id             bigint generated by default as identity primary key,
    kb_id          bigint      not null references knowledge_base (id),
    doc_id         bigint      not null references source_document (id),
    trigger_source varchar(16) not null,
    status         varchar(16) not null default 'QUEUED',
    phase          varchar(32),
    revision       integer,
    chunk_count    integer,
    error_message  varchar(4096),
    started_time   timestamptz,
    finished_time  timestamptz,
    heartbeat_time timestamptz,
    create_time    timestamptz not null default now(),

    constraint ck_ingestion_run_trigger check (trigger_source in ('MANUAL', 'SCHEDULED')),
    constraint ck_ingestion_run_status
        check (status in ('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'SKIPPED'))
);

create index idx_ingestion_run_doc on ingestion_run (doc_id, id desc);

-- 部分索引让轮询只扫待办的那几行：表会随历史记录持续增长，但待办永远只有几条，
-- 索引大小与历史总量无关。
create index idx_ingestion_run_pending on ingestion_run (id)
    where status in ('QUEUED', 'RUNNING');
